import argparse
import sys
from pathlib import Path

# Add scripts directory to sys.path to allow direct imports
SCRIPTS_DIR = Path(__file__).resolve().parent / "scripts"
sys.path.insert(0, str(SCRIPTS_DIR.parent)) # Add project root for `from scripts import ...`

from scripts import common_utils # To initialize DB early if needed for other direct script calls
from scripts.populate_kb import populate_knowledge_base
from scripts.generate_verif_plan import generate_verification_plan
from scripts.generate_c_tests import generate_c_test_from_description, parse_verification_plan_from_text

def main():
    parser = argparse.ArgumentParser(description="ASIC Verification Automation Orchestrator")
    subparsers = parser.add_subparsers(dest="command", help="Available commands", required=True)

    # Subparser for populating the knowledge base
    parser_populate = subparsers.add_parser("populate_kb", help="Process source documents and populate the RAG knowledge base (Vector DB).")
    parser_populate.set_defaults(func=handle_populate_kb)

    # Subparser for generating a verification plan
    parser_gen_plan = subparsers.add_parser("gen_plan", help="Generate a verification plan for a given ASIC feature.")
    parser_gen_plan.add_argument("feature_description", type=str, help="A description of the ASIC feature to verify (e.g., 'SPI controller master mode').")
    parser_gen_plan.add_argument("--output_format", type=str, default="structured text", choices=["structured text", "json", "csv"], help="Desired output format for the plan.")
    parser_gen_plan.set_defaults(func=handle_gen_plan)

    # Subparser for generating C tests
    parser_gen_tests = subparsers.add_parser("gen_tests", help="Generate C tests from a verification plan or a single test description.")
    parser_gen_tests.add_argument("--plan_file", type=str, help="Path to a verification plan text file (generated by gen_plan). If provided, all test cases in this plan will be processed.")
    parser_gen_tests.add_argument("--test_id", type=str, help="A specific Test ID for generating a single C test.")
    parser_gen_tests.add_argument("--test_desc", type=str, help="The description for a single test (required if --test_id is used and --plan_file is not).")
    parser_gen_tests.add_argument("--test_stimulus", type=str, default="Not specified.", help="Stimulus for the single test.")
    parser_gen_tests.add_argument("--test_expected", type=str, default="Not specified.", help="Expected outcome for the single test.")
    parser_gen_tests.add_argument("--c_example_file", type=str, help="Optional: Filename of a C test example (from knowledge_base_src/c_test_examples/) to strongly guide generation for a single test.")
    parser_gen_tests.add_argument("--limit", type=int, default=0, help="Limit the number of tests generated from a plan file (0 for all).")
    parser_gen_tests.set_defaults(func=handle_gen_tests)

    args = parser.parse_args()
    
    # Initialize common components like ChromaDB client (good to do it early)
    # Some scripts also call this, but doing it here ensures it's ready if needed.
    print("Initializing common utilities (e.g., ChromaDB client)...")
    common_utils.initialize_chromadb_client_and_collection()
    print("Initialization complete.")

    args.func(args)

def handle_populate_kb(args):
    print("Starting Knowledge Base Population...")
    populate_knowledge_base()
    print("Knowledge Base Population finished.")

def handle_gen_plan(args):
    print(f"Starting Verification Plan Generation for feature: {args.feature_description}")
    generate_verification_plan(args.feature_description, args.output_format)
    print("Verification Plan Generation finished.")

def handle_gen_tests(args):
    print("Starting C Test Generation...")
    if args.plan_file:
        plan_file_path = Path(args.plan_file)
        if not plan_file_path.is_file():
            print(f"Error: Verification plan file not found at {plan_file_path}")
            return
        try:
            with open(plan_file_path, 'r', encoding='utf-8') as f:
                plan_content = f.read()
            
            test_cases = parse_verification_plan_from_text(plan_content)
            if not test_cases:
                print("No test cases parsed from the plan file.")
                return

            num_to_process = len(test_cases)
            if args.limit > 0:
                num_to_process = min(len(test_cases), args.limit)
                print(f"Processing the first {num_to_process} test cases from the plan due to --limit.")

            for i in range(num_to_process):
                print(f"\nProcessing test case {i+1}/{num_to_process} from plan: {test_cases[i].get('test_id', 'N/A')}")
                generate_c_test_from_description(test_cases[i], preferred_c_example_source=args.c_example_file) # Can pass example for all from plan
                print("-" * 50)

        except Exception as e:
            print(f"Error processing plan file {plan_file_path}: {e}")

    elif args.test_id and args.test_desc:
        print(f"Generating single C test for Test ID: {args.test_id}")
        single_test_case = {
            "test_id": args.test_id,
            "test_description": args.test_desc,
            "stimulus": args.test_stimulus,
            "expected_outcome": args.test_expected
            # Other fields like category, feature can be added if needed by prompts
        }
        generate_c_test_from_description(single_test_case, preferred_c_example_source=args.c_example_file)
    else:
        print("For 'gen_tests', you must provide either --plan_file or both --test_id and --test_desc.")
        print("Use 'python main_orchestrator.py gen_tests --help' for more information.")

    print("C Test Generation finished.")


if __name__ == "__main__":
    main()