import os
import re
from pathlib import Path
import json # Or CSV parsing if plan is in CSV
from typing import List, Dict, Any, Optional
from .common_utils import call_deepseek_api, retrieve_relevant_chunks, load_prompt_template, OPENROUTER_API_KEY
from .automator import ASICVerificationAutomator

GENERATED_TESTS_PATH = Path(__file__).resolve().parent.parent / "generated_outputs" / "c_tests"

# Note: Macro definitions are now generated by LLM via prompt instructions
# instead of being hardcoded here. This provides more flexibility and
# maintains consistency with the reference examples.

def validate_c_test_structure(file_path: str) -> dict:
    """
    Validates the structure and content of a generated C test file.
    Returns a dictionary with validation results.
    """
    validation_result = {
        'is_valid': True,
        'errors': [],
        'warnings': [],
        'file_path': file_path
    }
    
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
    except Exception as e:
        validation_result['is_valid'] = False
        validation_result['errors'].append(f"Could not read file: {e}")
        return validation_result
    
    # Check if file is too short (likely incomplete)
    if len(content.strip()) < 100:
        validation_result['is_valid'] = False
        validation_result['errors'].append("File content is too short (likely incomplete)")
    
    # Check for required C test elements
    required_patterns = {
        'includes': r'#include\s*[<"].*[>"]',
        'function_definition': r'(int|void)\s+\w+\s*\([^)]*\)\s*\{',
        'test_logic': r'(printf|assert|return|if|while|for)',
        'proper_c_syntax': r'[;}]'
    }
    
    for element, pattern in required_patterns.items():
        if not re.search(pattern, content, re.MULTILINE | re.IGNORECASE):
            validation_result['is_valid'] = False
            validation_result['errors'].append(f"Missing required element: {element}")
    
    # Check for common issues
    
    # 1. Check if file contains only comments/text without actual C code
    code_lines = [line.strip() for line in content.split('\n') 
                  if line.strip() and not line.strip().startswith('//') 
                  and not line.strip().startswith('/*') and not line.strip().startswith('*')]
    
    if len(code_lines) < 5:  # Should have at least some lines of actual code
        validation_result['is_valid'] = False
        validation_result['errors'].append("File appears to contain mostly comments without substantial C code")
    
    # 2. Check for proper function structure
    if not re.search(r'\{[^}]*\}', content, re.DOTALL):
        validation_result['is_valid'] = False
        validation_result['errors'].append("No proper function body found (missing braces)")
    
    # 3. Check for HAL function usage (expected in CVA6 tests)
    hal_patterns = [
        r'hal_\w+',
        r'cva6_hal\.h',
        r'hal_cva6_\w+'
    ]
    
    has_hal_usage = any(re.search(pattern, content, re.IGNORECASE) for pattern in hal_patterns)
    if not has_hal_usage:
        validation_result['warnings'].append("No HAL function usage detected - may not be CVA6-specific")
    
    # 4. Check for test ID or test name
    test_id_patterns = [
        r'test_\w+',
        r'TEST_\w+',
        r'current_test_id_global'
    ]
    
    has_test_id = any(re.search(pattern, content, re.IGNORECASE) for pattern in test_id_patterns)
    if not has_test_id:
        validation_result['warnings'].append("No clear test ID or test name found")
    
    # 5. Check for syntax errors (basic)
    brace_count = content.count('{') - content.count('}')
    if brace_count != 0:
        validation_result['is_valid'] = False
        validation_result['errors'].append(f"Unmatched braces (difference: {brace_count})")
    
    paren_count = content.count('(') - content.count(')')
    if paren_count != 0:
        validation_result['is_valid'] = False
        validation_result['errors'].append(f"Unmatched parentheses (difference: {paren_count})")
    
    # 6. Check for incomplete generation (common LLM issue)
    incomplete_indicators = [
        r'\.\.\.',
        r'// TODO',
        r'// FIXME',
        r'<insert.*>',
        r'\[.*\].*implementation',
        r'This example demonstrates.*but.*would need.*adjusted'
    ]
    
    for pattern in incomplete_indicators:
        if re.search(pattern, content, re.IGNORECASE):
            validation_result['warnings'].append(f"Potential incomplete generation detected: {pattern}")
    
    return validation_result

def create_single_test_plan(verification_plan_text: str, target_test_id: str) -> str:
    """
    Extracts a single test case from the verification plan to create a focused plan
    for regenerating just that specific test.
    """
    # Split the plan into sections
    sections = re.split(r'### Test Case:', verification_plan_text)
    
    if len(sections) < 2:
        # Try alternative format (numbered list)
        sections = re.split(r'\d+\.\s*\*\*Test ID:\*\*', verification_plan_text)
    
    target_section = None
    for section in sections[1:]:  # Skip the first section (header)
        if target_test_id.upper() in section.upper():
            target_section = section
            break
    
    if not target_section:
        # Fallback: return the original plan
        return verification_plan_text
    
    # Create a minimal plan with just the target test
    header = sections[0] if sections else "# Verification Plan\n\n"
    
    # Reconstruct the test case in proper format
    if "### Test Case:" in verification_plan_text:
        single_test_plan = header + "### Test Case: " + target_section
    else:
        single_test_plan = header + "1. **Test ID:** " + target_section
    
    return single_test_plan

def check_and_regenerate_tests(
    verification_plan_text: str,
    output_dir: str,
    address_map_file_path: Optional[str] = None,
    hal_file_path: Optional[str] = None,
    test_example_file_path: Optional[str] = None,
    max_regeneration_attempts: int = 2
) -> dict:
    """
    Checks all generated C tests and regenerates any that are invalid.
    Returns a summary of validation and regeneration results.
    """
    output_path = Path(output_dir)
    if not output_path.exists():
        return {'error': f'Output directory does not exist: {output_dir}'}
    
    # Find all C test files
    c_files = list(output_path.glob('*.c'))
    if not c_files:
        return {'error': f'No C test files found in {output_dir}'}
    
    validation_summary = {
        'total_files': len(c_files),
        'valid_files': 0,
        'invalid_files': 0,
        'regenerated_files': 0,
        'failed_regenerations': 0,
        'details': []
    }
    
    print(f"\nValidating {len(c_files)} generated C test files...")
    
    for c_file in c_files:
        print(f"Checking: {c_file.name}")
        validation_result = validate_c_test_structure(str(c_file))
        
        file_detail = {
            'file': c_file.name,
            'original_valid': validation_result['is_valid'],
            'errors': validation_result['errors'],
            'warnings': validation_result['warnings'],
            'regenerated': False,
            'final_valid': validation_result['is_valid']
        }
        
        if validation_result['is_valid']:
            validation_summary['valid_files'] += 1
            print(f"  ✓ Valid")
            if validation_result['warnings']:
                print(f"  ⚠ Warnings: {'; '.join(validation_result['warnings'])}")
        else:
            validation_summary['invalid_files'] += 1
            print(f"  ✗ Invalid: {'; '.join(validation_result['errors'])}")
            
            # Attempt to regenerate the invalid test
            regeneration_success = False
            for attempt in range(max_regeneration_attempts):
                print(f"  🔄 Regeneration attempt {attempt + 1}/{max_regeneration_attempts}")
                
                try:
                    # Extract test ID from filename
                    test_id_match = re.search(r'test_(\w+)', c_file.stem)
                    if not test_id_match:
                        print(f"  ✗ Could not extract test ID from filename: {c_file.name}")
                        break
                    
                    test_id = test_id_match.group(1)
                    
                    # Create a focused verification plan for just this test
                    single_test_plan = create_single_test_plan(verification_plan_text, test_id)
                    
                    # Create a temporary directory for regeneration
                    temp_dir = output_path / f"temp_regen_{test_id}"
                    temp_dir.mkdir(exist_ok=True)
                    
                    # Parse test cases using the correct parser from automator
                    temp_automator = ASICVerificationAutomator(api_key=OPENROUTER_API_KEY)
                    parsed_test_cases = temp_automator._parse_test_cases_from_plan(single_test_plan)
                    
                    if parsed_test_cases:
                        # Regenerate using the existing function
                        regenerated_result = generate_c_test_from_description(parsed_test_cases[0])
                        
                        if regenerated_result:
                            # Check if the regenerated file exists and is valid
                            expected_file = GENERATED_TESTS_PATH / f"test_{test_id}.c"
                            if expected_file.exists():
                                new_validation = validate_c_test_structure(str(expected_file))
                                if new_validation['is_valid']:
                                    print(f"  ✓ Successfully regenerated and validated")
                                    file_detail['regenerated'] = True
                                    file_detail['final_valid'] = True
                                    validation_summary['regenerated_files'] += 1
                                    regeneration_success = True
                                else:
                                    print(f"  ✗ Regenerated file still invalid: {'; '.join(new_validation['errors'])}")
                            else:
                                print(f"  ✗ Regeneration failed - no file produced")
                    else:
                        print(f"  ✗ Could not parse test case from single test plan")
                        
                    # Clean up temp directory
                    if temp_dir.exists():
                        import shutil
                        shutil.rmtree(temp_dir, ignore_errors=True)
                    
                    if regeneration_success:
                        break
                        
                except Exception as e:
                    print(f"  ✗ Regeneration attempt failed: {e}")
                    # Clean up temp directory on error
                    if 'temp_dir' in locals() and temp_dir.exists():
                        import shutil
                        shutil.rmtree(temp_dir, ignore_errors=True)
            
            if not regeneration_success:
                validation_summary['failed_regenerations'] += 1
                print(f"  ✗ All regeneration attempts failed for {c_file.name}")
        
        validation_summary['details'].append(file_detail)
    
    # Print summary
    print(f"\n=== C Test Validation Summary ===")
    print(f"Total files: {validation_summary['total_files']}")
    print(f"Valid files: {validation_summary['valid_files']}")
    print(f"Invalid files: {validation_summary['invalid_files']}")
    print(f"Successfully regenerated: {validation_summary['regenerated_files']}")
    print(f"Failed regenerations: {validation_summary['failed_regenerations']}")
    
    return validation_summary

def verify_test_macros(file_path: str):
    """
    Verifies that essential test framework macros are present in the generated C test file.
    The macros should be generated by the LLM based on the reference examples.
    """
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()
        
        # List of essential macros that should be present
        essential_macros = ['VERIF_LOG', 'ASSERT_EQUAL', 'current_test_id_global']
        missing_macros = []
        
        for macro in essential_macros:
            if macro not in content:
                missing_macros.append(macro)
        
        if missing_macros:
            print(f"  ⚠ Warning: {Path(file_path).name} is missing essential macros: {', '.join(missing_macros)}")
            print(f"    The LLM should have included these based on the reference examples.")
            return False
        else:
            print(f"  ✓ Essential macros verified in {Path(file_path).name}")
            return True
        
    except Exception as e:
        print(f"  ✗ Error verifying macros in {file_path}: {e}")
        return False

def clean_llm_artifacts(content: str) -> str:
    """
    Removes common LLM artifacts from generated C code, including unwanted header text.
    """
    # Remove trailing markdown markers
    content = re.sub(r'```[a-zA-Z]*\s*$', '', content, flags=re.MULTILINE)
    content = re.sub(r'^```[a-zA-Z]*\s*', '', content, flags=re.MULTILINE)
    
    # Remove LLM-generated descriptive headers that appear before actual C code
    header_patterns = [
        r'^Here\'s?\s+the\s+complete\s+C\s+test\s+file.*?:\s*\n',
        r'^Here\s+the\s+C\s+test\s+function.*?:\s*\n',
        r'^Here\'s?\s+a\s+complete\s+C\s+test.*?:\s*\n',
        r'^Below\s+is\s+the\s+complete\s+C\s+test.*?:\s*\n',
        r'^This\s+is\s+the\s+complete\s+C\s+test.*?:\s*\n',
        r'^The\s+following\s+is\s+the\s+complete\s+C\s+test.*?:\s*\n',
        r'^Generated\s+C\s+test\s+code.*?:\s*\n',
    ]
    
    for pattern in header_patterns:
        content = re.sub(pattern, '', content, flags=re.IGNORECASE | re.MULTILINE)
    
    # Remove common LLM explanatory text at the end
    cleanup_patterns = [
        r'This is a.*?test.*?that.*?\.',
        r'The above.*?demonstrates.*?\.',
        r'Note that.*?would.*?need.*?to.*?be.*?\.',
        r'Remember to.*?adjust.*?according.*?to.*?\.',
        r'Please.*?modify.*?as.*?needed.*?\.',
        r'Notes?:\s*\n.*?(?=\n\s*\n|\Z)',  # Remove "Notes:" sections at the end
        r'The test.*?follows.*?structure.*?(?=\n\s*\n|\Z)',  # Remove structure explanations
        r'Consider.*?(?=\n\s*\n|\Z)',  # Remove "Consider..." suggestions
    ]
    
    for pattern in cleanup_patterns:
        content = re.sub(pattern, '', content, flags=re.IGNORECASE | re.DOTALL)
    
    # Remove extra whitespace
    content = re.sub(r'\n\s*\n\s*\n', '\n\n', content)
    
    return content.strip()

def generate_c_tests_from_plan(
    verification_plan_text: str, 
    address_map_file_path: Optional[str] = None, 
    hal_file_path: Optional[str] = None,
    test_example_file_path: Optional[str] = None,
    output_dir_name: str = "c_tests_generated",
    validate_and_regenerate: bool = True,
    output_dir: Optional[str] = None
) -> List[str]:
    """
    Uses ASICVerificationAutomator to generate C tests from a verification plan.
    Includes validation and regeneration of failed tests.
    `output_dir_name` is used if `output_dir` is not provided.
    Returns a list of paths to the generated C test files.
    """
    if not verification_plan_text:
        print("Error: Verification plan text cannot be empty.")
        return []

    print(f"\nInitializing RAG and Automator for C Test Generation...")
    
    try:
        automator = ASICVerificationAutomator(api_key=OPENROUTER_API_KEY)
    except ValueError as e:
        print(e)
        return []

    # Determine the actual output directory
    if output_dir:
        final_output_path = Path(output_dir)
    else:
        final_output_path = GENERATED_TESTS_PATH / output_dir_name
    
    final_output_path.mkdir(parents=True, exist_ok=True)
    print(f"Generated C tests will be saved in: {final_output_path}")

    # Load address map, HAL, and test example content
    address_map_text = ""
    if address_map_file_path:
        try:
            with open(address_map_file_path, "r", encoding="utf-8") as f:
                address_map_text = f.read()
            print(f"Loaded address map from: {address_map_file_path}")
        except IOError as e:
            print(f"Warning: Could not read address map file {address_map_file_path}: {e}")

    hal_text = ""
    if hal_file_path:
        try:
            with open(hal_file_path, "r", encoding="utf-8") as f:
                hal_text = f.read()
            print(f"Loaded HAL content from: {hal_file_path}")
        except IOError as e:
            print(f"Warning: Could not read HAL file {hal_file_path}: {e}")

    test_example_text = ""
    if test_example_file_path:
        try:
            with open(test_example_file_path, "r", encoding="utf-8") as f:
                test_example_text = f.read()
            print(f"Loaded test example content from: {test_example_file_path}")
        except IOError as e:
            print(f"Warning: Could not read test example file {test_example_file_path}: {e}")

    # Generate C tests
    generated_test_files = automator.generate_c_tests(
        verification_plan_text=verification_plan_text,
        address_map_text=address_map_text,
        hal_text=hal_text,
        test_example_text=test_example_text,
        output_dir=str(final_output_path)
    )

    if not generated_test_files:
        print("No C tests were generated by the automator.")
        return []

    print(f"\n--- Initial C Test Generation Summary ---")
    print(f"Successfully generated {len(generated_test_files)} C test files in {final_output_path}:")
    for test_file in generated_test_files:
        print(f"  - {test_file}")
    print("--- End of Initial Summary ---")

    # Add macro definitions to all generated test files
    print("\n--- Adding macro definitions to generated test files ---")
    for test_file in generated_test_files:
        verify_test_macros(test_file)

    if validate_and_regenerate:
        print("\n--- Starting Validation and Regeneration Process ---")
        regeneration_summary = check_and_regenerate_tests(
            verification_plan_text=verification_plan_text, 
            output_dir=str(final_output_path),
            address_map_file_path=address_map_file_path,
            hal_file_path=hal_file_path,
            test_example_file_path=test_example_file_path
        )
        print("--- End of Validation and Regeneration Process ---")

    # Ensure returned paths are absolute strings
    final_test_files = [str(Path(f).resolve()) for f in generated_test_files]
    return final_test_files

# Placeholder for parsing the verification plan.
# In a real system, this would parse a file (JSON, CSV, YAML, etc.)
# For this example, we'll assume a list of test case dictionaries.
def parse_verification_plan_from_text(plan_text: str) -> list[dict]:
    """
    Parses a structured text verification plan into a list of test case dictionaries.
    This is a very basic parser and highly dependent on the LLM's output format.
    It looks for "Test ID:" as a separator.
    """
    test_cases = []
    current_case_lines = []
    for line in plan_text.splitlines():
        if line.startswith("Test ID:") and current_case_lines:
            # Process previous case
            case_dict = {}
            full_case_text = "\n".join(current_case_lines)
            # Simple parsing - extract fields based on keywords
            for field_line in full_case_text.splitlines():
                if ":" in field_line:
                    key, value = field_line.split(":", 1)
                    key = key.strip().lower().replace(" ", "_").replace(":", "")
                    value = value.strip()
                    if key == "test_id": # Clean up test_id for function names
                        value = value.replace(" ", "_").replace("-", "_")
                    case_dict[key] = value
            if "test_id" in case_dict and "test_description" in case_dict: # Basic validation
                 test_cases.append(case_dict)
            current_case_lines = [line]
        else:
            current_case_lines.append(line)
    
    # Process the last case
    if current_case_lines:
        case_dict = {}
        full_case_text = "\n".join(current_case_lines)
        for field_line in full_case_text.splitlines():
            if ":" in field_line:
                key, value = field_line.split(":", 1)
                key = key.strip().lower().replace(" ", "_").replace(":", "")
                value = value.strip()
                if key == "test_id":
                    value = value.replace(" ", "_").replace("-", "_")
                case_dict[key] = value
        if "test_id" in case_dict and "test_description" in case_dict:
            test_cases.append(case_dict)
            
    print(f"Parsed {len(test_cases)} test cases from the plan.")
    if test_cases:
        print(f"First parsed test case ID: {test_cases[0].get('test_id')}")
    return test_cases


def generate_c_test_from_description(test_case: dict, preferred_c_example_source: str = None):
    """
    Generates a C test function for a single test case description.
    test_case should be a dictionary with keys like 'test_id', 'test_description', etc.
    """
    test_id = test_case.get("test_id", "unknown_test_id")
    test_description = test_case.get("test_description", "No description provided.")
    stimulus = test_case.get("stimulus", "Not specified.")
    expected_outcome = test_case.get("expected_outcome", "Not specified.")

    print(f"\nGenerating C test for Test ID: {test_id}")
    print(f"Description: {test_description[:100]}...")

    # 1. Retrieve relevant context using RAG
    hal_query = f"C HAL API functions for {test_description}"
    hal_context_chunks = retrieve_relevant_chunks(query_text=hal_query, top_k=3, doc_type_filter="hal_code") # or "hal_doc"
    if not hal_context_chunks: # Fallback if no hal_code found
        hal_context_chunks = retrieve_relevant_chunks(query_text=hal_query, top_k=3, doc_type_filter="hal_doc")

    regmap_query = f"Register details for {test_description}"
    regmap_context_chunks = retrieve_relevant_chunks(query_text=regmap_query, top_k=2, doc_type_filter="regmap")

    # Retrieve C test example
    example_c_source_description = "dynamically retrieved example"
    if preferred_c_example_source and (Path(preferred_c_example_source).is_file() or Path("knowledge_base_src/c_test_examples/") / preferred_c_example_source).is_file() :
        example_file_path_kb = Path("knowledge_base_src/c_test_examples/") / preferred_c_example_source
        example_file_path_abs = Path(preferred_c_example_source)

        actual_path = None
        if example_file_path_abs.is_file():
            actual_path = example_file_path_abs
        elif example_file_path_kb.is_file():
            actual_path = example_file_path_kb
        
        if actual_path:
            try:
                with open(actual_path, 'r', encoding='utf-8') as f:
                    c_example_context_chunks = [f.read()]
                example_c_source_description = f"user-specified file: {actual_path.name}"
                print(f"Using user-specified C example: {actual_path.name}")
            except IOError:
                print(f"Warning: Could not read user-specified example {actual_path}. Falling back to RAG.")
                c_example_context_chunks = retrieve_relevant_chunks(query_text=test_description, top_k=1, doc_type_filter="c_example")
        else:
            print(f"Warning: User-specified example '{preferred_c_example_source}' not found. Falling back to RAG.")
            c_example_context_chunks = retrieve_relevant_chunks(query_text=test_description, top_k=1, doc_type_filter="c_example")

    else:
        c_example_query = f"C test code example for {test_description}"
        c_example_context_chunks = retrieve_relevant_chunks(query_text=c_example_query, top_k=1, doc_type_filter="c_example")


    retrieved_hal_context = "\n\n---\n\n".join(hal_context_chunks) if hal_context_chunks else "No specific HAL details retrieved. Please ensure HAL functions are well-known or described in the test case."
    retrieved_regmap_context = "\n\n---\n\n".join(regmap_context_chunks) if regmap_context_chunks else "No specific register map details retrieved."
    retrieved_c_example_context = c_example_context_chunks[0] if c_example_context_chunks else "// No specific C test example retrieved. Adhere to general best practices for C tests."
    
    if not c_example_context_chunks and example_c_source_description == "dynamically retrieved example":
         example_c_source_description = "None found via RAG"


    # 2. Load prompt template
    prompt_template = load_prompt_template("stage2_c_test_gen_prompt.txt")
    if not prompt_template:
        print("Error: Could not load C test generation prompt template.")
        return

    # 3. Populate the prompt
    # Ensure test_id is clean for use in C function names
    clean_test_id = "".join(c if c.isalnum() or c == '_' else '_' for c in test_id)
    if not clean_test_id or clean_test_id[0].isdigit(): # C identifiers cannot start with a digit
        clean_test_id = "test_" + clean_test_id


    formatted_prompt = prompt_template.replace("{{test_id}}", clean_test_id)
    formatted_prompt = formatted_prompt.replace("{{test_description}}", test_description)
    formatted_prompt = formatted_prompt.replace("{{stimulus}}", stimulus)
    formatted_prompt = formatted_prompt.replace("{{expected_outcome}}", expected_outcome)
    formatted_prompt = formatted_prompt.replace("{{hal_context}}", retrieved_hal_context)
    formatted_prompt = formatted_prompt.replace("{{regmap_context}}", retrieved_regmap_context)
    formatted_prompt = formatted_prompt.replace("{{example_c_source_description}}", example_c_source_description)
    formatted_prompt = formatted_prompt.replace("{{example_c_code_context}}", retrieved_c_example_context)


    # 4. Call the LLM API
    print("Sending request to LLM for C test generation...")
    try:
        llm_response = call_deepseek_api(formatted_prompt, temperature=0.4, max_tokens=2048) # Temperature can be lower for code
    except Exception as e:
        print(f"Error calling LLM API: {e}")
        return

    if not llm_response or llm_response.startswith("Error:"):
        print(f"LLM API call failed or returned an error: {llm_response}")
        return    # 5. Save the generated C test
    GENERATED_TESTS_PATH.mkdir(parents=True, exist_ok=True)
    
    # Clean LLM artifacts before saving
    llm_response = clean_llm_artifacts(llm_response)
    
    output_filename = GENERATED_TESTS_PATH / f"test_{clean_test_id}.c"
    
    try:
        with open(output_filename, 'w', encoding='utf-8') as f:
            f.write(llm_response)
        print(f"\nC test function saved successfully to: {output_filename}")
        print("\n--- Generated C Test Snippet ---")
        print(llm_response[:500] + "..." if len(llm_response) > 500 else llm_response)
        print("--- End of Snippet ---")
    except IOError as e:
        print(f"Error saving C test to file: {e}")

    return llm_response


if __name__ == "__main__":
    # Example Usage:
    # This script can either process a full verification plan file
    # or a single hardcoded test case for demonstration.

    # Option 1: Process a verification plan file (e.g., generated by 02_generate_verif_plan.py)
    # Find the latest verification plan text file to process as an example
    plans_dir = Path(__file__).resolve().parent.parent / "generated_outputs" / "verification_plans"
    plan_files = sorted(plans_dir.glob("verif_plan_*.txt"), key=os.path.getmtime, reverse=True)

    if plan_files:
        latest_plan_file = plan_files[0]
        print(f"\nProcessing C tests from latest verification plan: {latest_plan_file.name}")
        try:
            with open(latest_plan_file, 'r', encoding='utf-8') as f:
                plan_content = f.read()
            
            test_cases_from_plan = parse_verification_plan_from_text(plan_content)
            
            if test_cases_from_plan:
                # Process only the first few test cases for this example run
                num_tests_to_generate = min(2, len(test_cases_from_plan)) # Limit to 2 for quick test
                print(f"Will generate C tests for the first {num_tests_to_generate} test cases from the plan.")
                for i in range(num_tests_to_generate):
                    generate_c_test_from_description(test_cases_from_plan[i])
                    print("-" * 50)
            else:
                print("No test cases could be parsed from the plan.")

        except Exception as e:
            print(f"Error processing plan file {latest_plan_file.name}: {e}")
            print("Consider using Option 2 (single test case) for testing C test generation.")

    else:
        print("\nNo verification plan files found in generated_outputs/verification_plans.")
        print("Consider running 02_generate_verif_plan.py first or use Option 2 below.")


    # Option 2: Define a single test case dictionary for quick testing
    # print("\n--- Testing with a single hardcoded test case ---")
    # example_single_test_case = {
    #     "test_id": "GPIO_TOGGLE_001",
    #     "test_category": "Basic IO",
    #     "feature_being_tested": "GPIO Output Toggle",
    #     "test_description": "Configure GPIO pin 5 as an output. Set GPIO pin 5 high. Read back GPIO data register to verify it is high. Set GPIO pin 5 low. Read back GPIO data register to verify it is low.",
    #     "stimulus": "1. Configure GPIO_CONF[5].DIR = OUTPUT. 2. Write GPIO_DATA[5] = 1. 3. Read GPIO_DATA[5]. 4. Write GPIO_DATA[5] = 0. 5. Read GPIO_DATA[5].",
    #     "expected_outcome": "1. GPIO_DATA[5] should read 1 after setting high. 2. GPIO_DATA[5] should read 0 after setting low.",
    #     "coverage_points": "GPIO output functionality. GPIO data register readback."
    # }
    # # You can also specify a C example file from your knowledge_base_src/c_test_examples/ directory
    # # e.g., generate_c_test_from_description(example_single_test_case, preferred_c_example_source="example_gpio_test.c")
    # generate_c_test_from_description(example_single_test_case)